name: fucking-test

on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: Deploy to IPv6 Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o ConnectTimeout=30 "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
            echo "fucking test"
          EOF